/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package editordetextoproyecto;

/**
 *
 * @author josue
 */
public class Ayuda extends javax.swing.JDialog {

    /**
     * Creates new form Ayuda
     */
    public Ayuda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        lblArchivo = new javax.swing.JLabel();
        lblNuevo = new javax.swing.JLabel();
        lblImageNuevo = new javax.swing.JLabel();
        lblOpen = new javax.swing.JLabel();
        lblOpenImage = new javax.swing.JLabel();
        lblGuardar = new javax.swing.JLabel();
        lblGuardaImage = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblExitImage = new javax.swing.JLabel();
        lblEdit = new javax.swing.JLabel();
        lblCopy = new javax.swing.JLabel();
        lblCopyImage = new javax.swing.JLabel();
        lblpaste = new javax.swing.JLabel();
        lblPasteImage = new javax.swing.JLabel();
        lblCut = new javax.swing.JLabel();
        lblCutImage = new javax.swing.JLabel();
        lblDeshacer = new javax.swing.JLabel();
        lblDeshacerImage = new javax.swing.JLabel();
        lblRehacer = new javax.swing.JLabel();
        lblRehacerImage = new javax.swing.JLabel();
        lblSelectionAll = new javax.swing.JLabel();
        lblSelectionImage = new javax.swing.JLabel();
        lblDiseño = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblColorImage = new javax.swing.JLabel();
        lblFuente = new javax.swing.JLabel();
        lblFunteImage = new javax.swing.JLabel();
        lblFontImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ayuda");
        setAlwaysOnTop(true);
        setName("Ayuda"); // NOI18N
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenida.setText("Accesos Directos");
        jPanel2.add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        lblArchivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblArchivo.setForeground(new java.awt.Color(255, 255, 255));
        lblArchivo.setText("Archivo");
        jPanel2.add(lblArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblNuevo.setText("Nuevo Ctrl+N");
        jPanel2.add(lblNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        lblImageNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nuevo.png"))); // NOI18N
        jPanel2.add(lblImageNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        lblOpen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblOpen.setForeground(new java.awt.Color(255, 255, 255));
        lblOpen.setText("Abrir Ctrl+O");
        jPanel2.add(lblOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        lblOpenImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/abrir.png"))); // NOI18N
        jPanel2.add(lblOpenImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        lblGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGuardar.setForeground(new java.awt.Color(255, 255, 255));
        lblGuardar.setText("Guardar Ctrl+S");
        jPanel2.add(lblGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        lblGuardaImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Guardar.png"))); // NOI18N
        lblGuardaImage.setToolTipText("");
        jPanel2.add(lblGuardaImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        lblExit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("Salir Ctrl+Q");
        jPanel2.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        lblExitImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Salir.png"))); // NOI18N
        jPanel2.add(lblExitImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 20, -1));

        lblEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblEdit.setText("Editar");
        jPanel2.add(lblEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        lblCopy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCopy.setForeground(new java.awt.Color(255, 255, 255));
        lblCopy.setText("Copiar Ctrl+V");
        jPanel2.add(lblCopy, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        lblCopyImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/copiar.png"))); // NOI18N
        jPanel2.add(lblCopyImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        lblpaste.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblpaste.setForeground(new java.awt.Color(255, 255, 255));
        lblpaste.setText("Pegar Ctrl+C");
        jPanel2.add(lblpaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        lblPasteImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pegar.png"))); // NOI18N
        jPanel2.add(lblPasteImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        lblCut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCut.setForeground(new java.awt.Color(255, 255, 255));
        lblCut.setText("Cortar Ctrl+X");
        jPanel2.add(lblCut, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        lblCutImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cortar.png"))); // NOI18N
        jPanel2.add(lblCutImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        lblDeshacer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDeshacer.setForeground(new java.awt.Color(255, 255, 255));
        lblDeshacer.setText("Deshacer Ctrl+Z");
        jPanel2.add(lblDeshacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        lblDeshacerImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/deshacer .png"))); // NOI18N
        jPanel2.add(lblDeshacerImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        lblRehacer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRehacer.setForeground(new java.awt.Color(255, 255, 255));
        lblRehacer.setText("Rehacer Ctrl+Y");
        jPanel2.add(lblRehacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        lblRehacerImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rehacer .png"))); // NOI18N
        jPanel2.add(lblRehacerImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        lblSelectionAll.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSelectionAll.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectionAll.setText("Seleccionar todo Ctrl+A");
        jPanel2.add(lblSelectionAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        lblSelectionImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Seleccionar_todo.png"))); // NOI18N
        jPanel2.add(lblSelectionImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, -1));

        lblDiseño.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDiseño.setForeground(new java.awt.Color(255, 255, 255));
        lblDiseño.setText("Diseño");
        jPanel2.add(lblDiseño, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        lblColor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblColor.setForeground(new java.awt.Color(255, 255, 255));
        lblColor.setText("Color Ctrl+1");
        jPanel2.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        lblColorImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/texto-en-color.png"))); // NOI18N
        jPanel2.add(lblColorImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        lblFuente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFuente.setForeground(new java.awt.Color(255, 255, 255));
        lblFuente.setText("Fuente Ctrl + F");
        jPanel2.add(lblFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        lblFunteImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/editar-texto.png"))); // NOI18N
        jPanel2.add(lblFunteImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        lblFontImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Fuente2.1.png"))); // NOI18N
        jPanel2.add(lblFontImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ayuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ayuda dialog = new Ayuda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColorImage;
    private javax.swing.JLabel lblCopy;
    private javax.swing.JLabel lblCopyImage;
    private javax.swing.JLabel lblCut;
    private javax.swing.JLabel lblCutImage;
    private javax.swing.JLabel lblDeshacer;
    private javax.swing.JLabel lblDeshacerImage;
    private javax.swing.JLabel lblDiseño;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblExitImage;
    private javax.swing.JLabel lblFontImage;
    private javax.swing.JLabel lblFuente;
    private javax.swing.JLabel lblFunteImage;
    private javax.swing.JLabel lblGuardaImage;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblImageNuevo;
    private javax.swing.JLabel lblNuevo;
    private javax.swing.JLabel lblOpen;
    private javax.swing.JLabel lblOpenImage;
    private javax.swing.JLabel lblPasteImage;
    private javax.swing.JLabel lblRehacer;
    private javax.swing.JLabel lblRehacerImage;
    private javax.swing.JLabel lblSelectionAll;
    private javax.swing.JLabel lblSelectionImage;
    private javax.swing.JLabel lblpaste;
    // End of variables declaration//GEN-END:variables
}
